name: Notify Private Repo of Changes

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "content/recipes/**"
  workflow_dispatch:

jobs:
  notify_changes:
    # Only run this job when a PR is merged
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Generate GitHub App Token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          repository: your-username/private-recipes-repo  # Change this to your private repo

      - name: Trigger workflow in private repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: iammatthias/obsidian_cms
          event-type: public-repo-updated
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "pr_number": "${{ github.event.pull_request.number }}", "pr_title": "${{ github.event.pull_request.title }}"}'
